In [ ]:
import numpy as np

print("\n🔹 Special Arrays:")
print("Zeros:\n", np.zeros((2, 3)))
print("Ones:\n", np.ones((3, 2)))
print("Identity matrix:\n", np.eye(3))
print("Random values:\n", np.random.rand(2, 2))
print("Arange:\n", np.arange(0, 10, 2))
print("Linspace:\n", np.linspace(0, 10, 5))


🔹 Special Arrays:
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random values:
 [[0.9441862  0.82134862]
 [0.98036563 0.65962185]]
Arange:
 [0 2 4 6 8]
Linspace:
 [ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print("Shape:", arr_1d.shape)
print("Number of dimensions:", arr_1d.ndim)
print("Size:", arr_1d.size)
print()

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print("Shape:", arr_2d.shape)
print("Number of dimensions:", arr_2d.ndim)
print("Size:", arr_2d.size)
print()

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:")
print("Shape:", arr_3d.shape)
print("Number of dimensions:", arr_3d.ndim)
print("Size:", arr_3d.size)
print()

1D Array:
Shape: (5,)
Number of dimensions: 1
Size: 5

2D Array:
Shape: (2, 3)
Number of dimensions: 2
Size: 6

3D Array:
Shape: (2, 2, 2)
Number of dimensions: 3
Size: 8



In [ ]:
arr = np.array([10, 20, 30, 40, 40])
print(np.mean(arr))   # Mean
print(np.median(arr)) # Median

print(np.min(arr))    # Minimum
print(np.max(arr))    # Maximum
print(np.sum(arr))    # Sum of elements

print("\n🔹 Sorting and Unique:")
d = np.array([3, 1, 2, 3])
print("Sorted:", np.sort(d))
print("Unique values:", np.unique(d))

28.0
30.0
10
40
140

🔹 Sorting and Unique:
Sorted: [1 2 3 3]
Unique values: [1 2 3]


In [ ]:
# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Scalar to 1D array addition
result_scalar_add = arr_1d + 2
print("Scalar addition:", result_scalar_add)

# Scalar to 1D array multiplication
result_scalar_mul = arr_1d * 3
print("Scalar multiplication:", result_scalar_mul)

# 1D array to 1D array addition (assuming equal length)
arr_1d_2 = np.array([6, 7, 8, 9,10])
result_array_add = arr_1d + arr_1d_2
print("Array addition:", result_array_add)

# 1D array to 1D array multiplication (assuming equal length)
result_array_mul = arr_1d * arr_1d_2
print("Array multiplication:", result_array_mul)

arr_dif = arr_1d - arr_1d_2
print("Array subtraction:", arr_dif)


Scalar addition: [3 4 5 6 7]
Scalar multiplication: [ 3  6  9 12 15]
Array addition: [ 7  9 11 13 15]
Array multiplication: [ 6 14 24 36 50]
Array subtraction: [-5 -5 -5 -5 -5]


In [ ]:
import time
import numpy as np

# Size of the dataset
N = 10_000_000

# ----------------------
# Using Python List
# ----------------------
list1 = list(range(N))
list2 = list(range(N))

start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
end_time = time.time()
print("Time taken using Python List:", round(end_time - start_time, 4), "seconds")

# ----------------------
# Using NumPy Array
# ----------------------
array1 = np.arange(N)
array2 = np.arange(N)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print("Time taken using NumPy Array:", round(end_time - start_time, 4), "seconds")


Time taken using Python List: 0.6556 seconds
Time taken using NumPy Array: 0.0386 seconds


In [ ]:
# Reshaping
arr = np.array([1, 2, 3, 4, 5, 6])
print("Reshape (2x3): ")
print(arr.reshape(2,3))  # Convert 1D to 2D (2x3)
print("Reshape (3x2): ")
print(arr.reshape(3,2))

# Flttening
arr = np.array([[1, 2], [3, 4]])
print("Flatten: ",arr.flatten())  # [1 2 3 4]

# Transpose
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Transpose: ")
print(arr.T)  # Swap rows and columns


Reshape (2x3): 
[[1 2 3]
 [4 5 6]]
Reshape (3x2): 
[[1 2]
 [3 4]
 [5 6]]
Flatten:  [1 2 3 4]
Transpose: 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", arr2d)

# Accessing elements in a 2D array
print("Element at row 0, column 1:", arr2d[0, 1])
print("Element at row 2, column 2:", arr2d[2, 2])

# Slicing a 2D array
print("Row 0:", arr2d[0, :])
print("Column 1:", arr2d[:, 1])
print("Subarray:\n", arr2d[:3, :2])


2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, column 1: 2
Element at row 2, column 2: 9
Row 0: [1 2 3]
Column 1: [2 5 8]
Subarray:
 [[1 2]
 [4 5]
 [7 8]]
